### ISSUE TITLE
Make edlfs GitHub Container Registry packages public

### ISSUE THREAD

**Issue by jhkennedy** [jhkennedy/edlfs#5]
It looks like an organization admin will have to make the docker container images public. This can be done by following this link:
https://github.com/orgs/NASA-Openscapes/packages/container/edlfs/settings

Scrolling to the bottom to the "Danger Zone, selecting "Change Visibility", and selecting "Public"

![image](https://user-images.githubusercontent.com/7882693/206380125-281236bd-f7e2-4f5a-8aae-2d05e1a37dc1.png)

@betolink do you have, or know who has, the power? @jules32  or @erinmr, maybe?

**Comment by betolink** [comment]
I'm not an org admin, I think @jules32 is the admin.

**Comment by jules32** [comment]
Yes! Thanks for the screenshot and description, it's done! (I didn't know you could have part of a public repository be private, (if that's what's going on here?) that's cool).

**Comment by jhkennedy** [comment]
@jules32 I'm still seeing the packages as marked as private :thinking:

**Comment by jhkennedy** [comment]
And yes, packages are always private by default on GitHub; they need to be explicitly made public.

**Comment by jules32** [comment]
Sorry @jhkennedy . I have changed the settings and it still says its disabled; I've filed a ticket with GitHub and will give an update as soon as I have it

**Comment by erinmr** [comment]
@jules32, I think I switched our org settings to make this work. @jhkennedy - i checked public. Let me know if this doesn't fix it?

**Comment by jhkennedy** [comment]
@jules32 @erinmr that did it! Thank you so much! 🙏
